MINER:
  STONE: 1
  DIORITE: 1
  GRANITE: 1
  ANDESITE: 1
  TUFF: 1
  IRON_ORE: 1
  COPPER_ORE: 1
  GOLD_ORE: 2
  COAL_ORE: 1
  LAPIS_ORE: 2
  REDSTONE_ORE: 1
  EMERALD_ORE: 10
  DIAMOND_ORE: 5
  DEEPSLATE: 1
  DEEPSLATE_COAL_ORE: 1
  DEEPSLATE_IRON_ORE: 1
  DEEPSLATE_COPPER_ORE: 1
  DEEPSLATE_GOLD_ORE: 2
  DEEPSLATE_LAPIS_ORE: 2
  DEEPSLATE_REDSTONE_ORE: 1
  DEEPSLATE_EMERALD_ORE: 10
  DEEPSLATE_DIAMOND_ORE: 5
  NETHER_QUARTZ_ORE: 1
  ANCIENT_DEBRIS: 10
  NETHER_GOLD_ORE: 2
LUMBER:
  OAK_LOG: 1
  SPRUCE_LOG: 1
  BIRCH_LOG: 1
  JUNGLE_LOG: 1
  ACACIA_LOG: 1
  DARK_OAK_LOG: 1