use_mysql: false
mysql_host: localhost
mysql_port: 3306
mysql_username: uwuJobs
mysql_password: password
mysql_database: uwuJobs

# Sets the time for when to flush jobs data to database
save_interval: 10

auto-update: false #Experimental