MINER:
  STONE: 1
  DIORITE: 1
  GRANITE: 1
  ANDESITE: 1
  TUFF: 1
  IRON_ORE: 2
  COPPER_ORE: 2
  GOLD_ORE: 3
  COAL_ORE: 2
  LAPIS_ORE: 3
  REDSTONE_ORE: 2
  EMERALD_ORE: 13
  DIAMOND_ORE: 6
  DEEPSLATE: 1
  DEEPSLATE_COAL_ORE: 2
  DEEPSLATE_IRON_ORE: 2
  DEEPSLATE_COPPER_ORE: 2
  DEEPSLATE_GOLD_ORE: 3
  DEEPSLATE_LAPIS_ORE: 3
  DEEPSLATE_REDSTONE_ORE: 2
  DEEPSLATE_EMERALD_ORE: 11
  DEEPSLATE_DIAMOND_ORE: 6
  NETHER_QUARTZ_ORE: 2
  ANCIENT_DEBRIS: 13
  NETHER_GOLD_ORE: 2
  SANDSTONE: 1
LUMBER:
  OAK_LOG: 1
  SPRUCE_LOG: 1
  BIRCH_LOG: 1
  JUNGLE_LOG: 1
  ACACIA_LOG: 1
  DARK_OAK_LOG: 1
  WARPED_STEM: 1
FARMER:
  CARROTS: 1
  POTATOES: 1
  WHEAT: 1
  NETHER_WART: 1
  BEETROOTS: 1
SHOVELER:
  CLAY: 1
  COARSE_DIRT: 1
  WHITE_CONCRETE_POWDER: 1
  ORANGE_CONCRETE_POWDER: 1
  MAGENTA_CONCRETE_POWDER: 1
  LIGHT_BLUE_CONCRETE_POWDER: 1
  YELLOW_CONCRETE_POWDER: 1
  LIME_CONCRETE_POWDER: 1
  PINK_CONCRETE_POWDER: 1
  GRAY_CONCRETE_POWDER: 1
  LIGHT_GRAY_CONCRETE_POWDER: 1
  CYAN_CONCRETE_POWDER: 1
  PURPLE_CONCRETE_POWDER: 1
  BLUE_CONCRETE_POWDER: 1
  BROWN_CONCRETE_POWDER: 1
  GREEN_CONCRETE_POWDER: 1
  RED_CONCRETE_POWDER: 1
  BLACK_CONCRETE_POWDER: 1
  DIRT: 1
  DIRT_PATH: 1
  FARMLAND: 1
  GRASS_BLOCK: 1
  GRAVEL: 1
  MUD: 1
  MUDDY_MANGROVE_ROOTS: 1
  MYCELIUM: 1
  PODZOL: 1
  RED_SAND: 1
  ROOTED_DIRT: 1
  SAND: 1
  SNOW: 1
  SNOW_BLOCK: 1
  SOUL_SAND: 1
  SOUL_SOIL: 1
  SUSPICIOUS_GRAVEL: 1
  SUSPICIOUS_SAND: 1