name: Build Gradle project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Run build
        run: gradle shadowJar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: uwuJobs
          path: build/libs/uwuJobs?*.jar
